name: Build Repository WF
on: #TRIGGERS
    push: # On  push
        branches: [master] #on brnaches

jobs:
    BuildJob: # Job name
        runs-on: ubuntu-latest # Operating system selection
        env: # Environment can be controlled at the job or step level
            TERM: dumb #no prints
        steps:
            - name: Clone Repo with Checkout # first step
              uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
            - name: Install JDK
              uses: joschi/setup-jdk@v2.3.0 # download jdk! Action implemented in repository "joschi/setup-jdk" tag "2.3.0"
              with: # Actions parameters (action name omitted)
                java-version: 15
            - name: Build and Check :P #cusom action
              run: ./gradlew clean build #performs gradlew build, it check if present checkstyle, it runs test with junit, it assembles the jar
    TelegramJobFailure:
        if: failure() # when fails
        needs: [BuildJob] #when finished this job
        runs-on: ubuntu-latest
        steps:
        - name: send custom message with args
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
                ${{ github.event_name }} event,
                on github.com/${{ github.repository }}, 
                by ${{ github.actor }}.
                FAILED
            disable_web_page_preview: true
    TelegramJobSuccess:
        if: success() # when fails
        needs: [BuildJob] #when finished this job
        runs-on: ubuntu-latest
        steps:
        - name: send custom message with args
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
                ${{ github.event_name }} event,
                on github.com/${{ github.repository }}, 
                by ${{ github.actor }}.
                SUCCEDED
            disable_web_page_preview: true
