name: Email WorkFlow
on: #TRIGGERS
    push: # On  push
        branches: [master] #on branches

jobs:
  EmailJob:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - name: Clone Repo with Checkout # first step
      uses: actions/checkout@v2 # clones repo! Action implemented in this repository, tag "2"
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Required mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: lirussi-sp@yahoo.com
        # Required sender full name (address can be skipped):
        from: SmarDoggo # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully this time, for real!
        # Optional carbon copy recipients:
        cc: gxe23786@eoopy.com
        # Optional recipient of the email response:
        reply_to: gxe23786@eoopy.com
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
