name: Telegram Message WF
on: #TRIGGERS
    push: # On  push
        branches: [master] #on brnaches

jobs:
  TelegramJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom telegram message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.event_name }} event,
            on github.com/${{ github.repository }}, 
            by ${{ github.actor }}.
        disable_web_page_preview: true
        document: main.pdf
